
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lpkjahhydmnlumchdzxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxwa2phaGh5ZG1ubHVtY2hkenhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMzI2ODIsImV4cCI6MjA1NzkwODY4Mn0.NdFGkx2fdyS7arQUoWHcGcYXqTaBtVC4U9428-QY2aA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});
